#!/bin/sh /etc/rc.common
START=25
start() {
  if [ ! -f /etc/firehol/fireqos.conf ]
  then
    echo "Install /etc/firehol/fireqos.conf"
    echo "  (for an example, see /etc/firehol/fireqos.conf.example)"
    echo "and test it with:"
    echo "  fireqos start"
    exit 1
  fi
  if [ -x /sbin/insmod -a ! -x /sbin/modprobe ]
  then
    echo "/sbin/insmod" > /proc/sys/kernel/modprobe
  fi
  /sbin/fireqos start
}
restart() {
  /sbin/fireqos start
}
reload() {
  /sbin/fireqos start
}
stop() {
  /sbin/fireqos stop
}
